---
labels: [show-and-tell]
body:
  - type: markdown
    attributes:
      value: |
        Share how you're using the Meal Plan Management Service! Your implementations might help others.

  - type: textarea
    attributes:
      label: What Did You Build?
      description: Describe your implementation or integration
      placeholder: Tell us about your project...
    validations:
      required: true

  - type: textarea
    attributes:
      label: How Are You Using the Meal Plan Service?
      description: How does the meal plan service fit into your architecture?
      placeholder: |
        - Integration details
        - Client implementation
        - Deployment setup
        - Use cases

  - type: textarea
    attributes:
      label: Interesting Challenges or Solutions
      description: Any interesting problems you solved or lessons learned?
      placeholder: Share your experience...

  - type: textarea
    attributes:
      label: Screenshots or Demo
      description: Show us what you built!
      placeholder: Links to screenshots, demos, repositories, etc.

  - type: textarea
    attributes:
      label: Feedback for the Project
      description: Any feedback or suggestions based on your experience?
      placeholder: What worked well? What could be improved?
