---
# k8s/configmap-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: meal-plan-management-config
  namespace: meal-plan-management
  labels:
    app: meal-plan-management-service
data:
  # Application Configuration
  NODE_ENV: '${NODE_ENV}'
  MEAL_PLAN_SERVICE_SERVER_HOST: '${MEAL_PLAN_SERVICE_SERVER_HOST}'
  MEAL_PLAN_SERVICE_SERVER_PORT: '${MEAL_PLAN_SERVICE_SERVER_PORT}'
  MEAL_PLAN_SERVICE_SERVER_MAX_UPLOAD_SIZE: '${MEAL_PLAN_SERVICE_SERVER_MAX_UPLOAD_SIZE}'

  # Database Configuration (non-sensitive)
  POSTGRES_HOST: '${POSTGRES_HOST}'
  POSTGRES_PORT: '${POSTGRES_PORT}'
  POSTGRES_DB: '${POSTGRES_DB}'
  POSTGRES_SCHEMA: '${POSTGRES_SCHEMA}'
  MEAL_PLAN_MANAGEMENT_DB_USER: '${MEAL_PLAN_MANAGEMENT_DB_USER}'
  DATABASE_MAX_CONNECTIONS: '${DATABASE_MAX_CONNECTIONS}'
  DATABASE_MIN_CONNECTIONS: '${DATABASE_MIN_CONNECTIONS}'
  DATABASE_ACQUIRE_TIMEOUT_SECONDS: '${DATABASE_ACQUIRE_TIMEOUT_SECONDS}'

  # Storage Configuration
  MEAL_PLAN_SERVICE_STORAGE_BASE_PATH: '${MEAL_PLAN_SERVICE_STORAGE_BASE_PATH}'
  MEAL_PLAN_SERVICE_STORAGE_TEMP_PATH: '${MEAL_PLAN_SERVICE_STORAGE_TEMP_PATH}'
  MEAL_PLAN_SERVICE_STORAGE_MAX_FILE_SIZE: '${MEAL_PLAN_SERVICE_STORAGE_MAX_FILE_SIZE}'

  # JWT Configuration (non-sensitive)
  JWT_EXPIRES_IN: '${JWT_EXPIRES_IN}'

  # Redis Configuration (non-sensitive)
  REDIS_HOST: '${REDIS_HOST}'
  REDIS_PORT: '${REDIS_PORT}'

  # External Services
  RECIPE_SERVICE_URL: '${RECIPE_SERVICE_URL}'
  USER_SERVICE_URL: '${USER_SERVICE_URL}'

  # Rate Limiting
  RATE_LIMIT_TTL: '${RATE_LIMIT_TTL}'
  RATE_LIMIT_MAX: '${RATE_LIMIT_MAX}'

  # CORS
  CORS_ORIGINS: '${CORS_ORIGINS}'

  # OAuth2 Configuration
  OAUTH2_SERVICE_ENABLED: '${OAUTH2_SERVICE_ENABLED}'
  OAUTH2_SERVICE_TO_SERVICE_ENABLED: '${OAUTH2_SERVICE_TO_SERVICE_ENABLED}'
  OAUTH2_INTROSPECTION_ENABLED: '${OAUTH2_INTROSPECTION_ENABLED}'
  OAUTH2_CLIENT_ID: '${OAUTH2_CLIENT_ID}'

  # Logging Configuration
  MEAL_PLAN_SERVICE_LOGGING_LEVEL: '${MEAL_PLAN_SERVICE_LOGGING_LEVEL}'
  MEAL_PLAN_SERVICE_LOGGING_FORMAT: '${MEAL_PLAN_SERVICE_LOGGING_FORMAT}'
