---
name: Security Vulnerability (Public)
description: Report a low-severity security issue (use GitHub Security Advisories for critical issues)
title: '[Security]: '
labels: ['security', 'needs-triage']
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For critical security vulnerabilities, please use
        [GitHub Security Advisories][security-advisories] instead of this
        public form.

        [security-advisories]: https://github.com/Recipe-Web-App/meal-plan-management-service/security/advisories/new

        Use this form only for:
        - Low-severity security concerns
        - Security improvements
        - Best practice suggestions
        - Dependency vulnerabilities (also reported by Dependabot)

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low (Informational/Best Practice)
        - Medium (Requires specific conditions to exploit)
        - High (Should use GitHub Security Advisories instead)
        - Critical (Should use GitHub Security Advisories instead)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern or vulnerability
      placeholder: Please provide a clear description of the security issue
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - JWT/Token Security
        - Input Validation
        - Cryptography
        - Dependency Vulnerability
        - Information Disclosure
        - Rate Limiting/DoS
        - CORS/Security Headers
        - Secret Management
        - Database Security (Prisma/PostgreSQL)
        - API Security
        - NestJS Security
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially achieve?
      placeholder: Describe the potential security impact
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: How can this security issue be demonstrated?
      placeholder: |
        1. Configure service with...
        2. Send request to /api/v1/...
        3. Observe...

  - type: textarea
    id: recommendation
    attributes:
      label: Recommended Fix
      description: Do you have suggestions for fixing this issue?
      placeholder: Describe how this could be remediated

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which parts of the service are affected?
      placeholder: List affected endpoints, modules, or configurations
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details where this was discovered
      value: |
        - Version/Commit:
        - Node.js version:
        - Deployment type:
        - Configuration:

  - type: checkboxes
    id: responsible
    attributes:
      label: Responsible Disclosure
      description: Please confirm
      options:
        - label: I understand critical vulnerabilities should be reported privately via GitHub Security Advisories
          required: true
        - label: This is a low-severity issue appropriate for public discussion
          required: true
        - label: I will not publicly disclose exploit details until a fix is available
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information
      placeholder: References, similar issues in other projects, etc.
