name: Greet First-Time Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greet:
    name: Greet New Contributors
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time issue creator
        if: github.event_name == 'issues'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 **Welcome to the Meal Plan Management Service!**

            Thank you for opening your first issue! We appreciate your
            contribution to the project.

            Here are some helpful resources:
            - [Contributing Guide][contributing]
            - [Support Documentation][support]
            - [Code of Conduct][coc]

            A maintainer will review your issue soon. Thanks for your patience!

            [contributing]: https://github.com/Recipe-Web-App/meal-plan-management-service/blob/main/.github/CONTRIBUTING.md
            [support]: https://github.com/Recipe-Web-App/meal-plan-management-service/blob/main/.github/SUPPORT.md
            [coc]: https://github.com/Recipe-Web-App/meal-plan-management-service/blob/main/.github/CODE_OF_CONDUCT.md

      - name: Greet first-time PR creator
        if: github.event_name == 'pull_request_target'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            🎉 **Congratulations on your first Pull Request!**

            Thank you for contributing to the Meal Plan Management Service! We're excited to review your changes.

            Before merging, please ensure:
            - [ ] All tests pass (`npm test`)
            - [ ] Code follows our style guide (`npm run lint`)
            - [ ] Documentation is updated if needed
            - [ ] Commits follow [conventional commit format](https://www.conventionalcommits.org/)

            A maintainer will review your PR soon. Thank you for your contribution!
